package org.lanqiao.bank.base.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.lanqiao.bank.base.dto.Pager;
import org.lanqiao.bank.base.entity.Bank;
import org.lanqiao.bank.base.entity.BankExample;

/**
 * @ClassName: BankDao
 * @Description: 银行持久层接口
 * @author 西安工业大学蓝桥学员-苏杰
 * @time 2017年4月24日 上午10:46:36
 */
@Deprecated
public interface BankDao {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bank
	 *
	 * @mbg.generated Wed May 03 20:59:30 CST 2017
	 */
	long countByExample(BankExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bank
	 *
	 * @mbg.generated Wed May 03 20:59:30 CST 2017
	 */
	int deleteByExample(BankExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bank
	 *
	 * @mbg.generated Wed May 03 20:59:30 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bank
	 *
	 * @mbg.generated Wed May 03 20:59:30 CST 2017
	 */
	int insert(Bank record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bank
	 *
	 * @mbg.generated Wed May 03 20:59:30 CST 2017
	 */
	int insertSelective(Bank record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bank
	 *
	 * @mbg.generated Wed May 03 20:59:30 CST 2017
	 */
	List<Bank> selectByExample(@Param("example")BankExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bank
	 *
	 * @mbg.generated Wed May 03 20:59:30 CST 2017
	 */
	Bank selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bank
	 *
	 * @mbg.generated Wed May 03 20:59:30 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Bank record, @Param("example") BankExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bank
	 *
	 * @mbg.generated Wed May 03 20:59:30 CST 2017
	 */
	int updateByExample(@Param("record") Bank record, @Param("example") BankExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bank
	 *
	 * @mbg.generated Wed May 03 20:59:30 CST 2017
	 */
	int updateByPrimaryKeySelective(Bank record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bank
	 *
	 * @mbg.generated Wed May 03 20:59:30 CST 2017
	 */
	int updateByPrimaryKey(Bank record);
}