package org.lanqiao.bank.base.entity;

import java.util.Date;

/**
 * @ClassName: Bank 
 * @Description: 银行实体
 * @author 西安工业大学蓝桥学员-苏杰
 * @time 2017年5月3日 下午9:00:11
 */
@Deprecated
public class Bank {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank.id
     *
     * @mbg.generated Wed May 03 20:59:30 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank.name
     *
     * @mbg.generated Wed May 03 20:59:30 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank.update_time
     *
     * @mbg.generated Wed May 03 20:59:30 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank.create_time
     *
     * @mbg.generated Wed May 03 20:59:30 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank.pic
     *
     * @mbg.generated Wed May 03 20:59:30 CST 2017
     */
    private String pic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank.id
     *
     * @return the value of bank.id
     *
     * @mbg.generated Wed May 03 20:59:30 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank.id
     *
     * @param id the value for bank.id
     *
     * @mbg.generated Wed May 03 20:59:30 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank.name
     *
     * @return the value of bank.name
     *
     * @mbg.generated Wed May 03 20:59:30 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank.name
     *
     * @param name the value for bank.name
     *
     * @mbg.generated Wed May 03 20:59:30 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank.update_time
     *
     * @return the value of bank.update_time
     *
     * @mbg.generated Wed May 03 20:59:30 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank.update_time
     *
     * @param updateTime the value for bank.update_time
     *
     * @mbg.generated Wed May 03 20:59:30 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank.create_time
     *
     * @return the value of bank.create_time
     *
     * @mbg.generated Wed May 03 20:59:30 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank.create_time
     *
     * @param createTime the value for bank.create_time
     *
     * @mbg.generated Wed May 03 20:59:30 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank.pic
     *
     * @return the value of bank.pic
     *
     * @mbg.generated Wed May 03 20:59:30 CST 2017
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank.pic
     *
     * @param pic the value for bank.pic
     *
     * @mbg.generated Wed May 03 20:59:30 CST 2017
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }
}